language: scala
script:
  - sbt ++2.11.8 readme/run
  - sbt ++$TRAVIS_SCALA_VERSION scalatagsJVM/test scalatagsJS/test
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0-RC2
jdk:
  - openjdk7
  - oraclejdk8
matrix:
  exclude:
    - scala: 2.12.0-RC2
      jdk: openjdk7
sudo: false
